### ISSUE TITLE
8 bit read/writes should not send an Endianness argument

### ISSUE THREAD

**Issue by matthewleon** [purescript-contrib/purescript-arraybuffer#10]
This appears to be ignored, but there shouldn't be any reason to send it in the first place.

**Comment by jacereda** [comment]
It's passed to avoid a specific JS implementation for the 8 bit case. If you're worried about performance then probably it would be better to implement specific getters/setters for each word size, since I guess something like `dv.getInt8()` should be faster than `dv['getInt8']()` (but don't take my word on that, I'm not very familiar with JS JITs).
